argv<-commandArgs(TRUE)
eachM<-argv[1]
expDat<-argv[2]
each<-read.csv(eachM,sep=",",header=T)
exp<-read.csv(expDat,sep=",",header=T)
exp<-exp[,c("fn","id","is_merged","time_close")]
exp$is_merged<-ifelse(exp$is_merged=="True",1,0)
names(each)<-c("id","fn","cb","pr")
each<-na.omit(each)
each$diff<-abs(each$cb-each$pr)
all<-merge(exp,each,by=c("fn","id"))
print(c(nrow(each),nrow(exp),nrow(all)))
each_corr=cor.test(x=all$diff,y=all$is_merged,method="spearman")$estimate
each_p_value=cor.test(x=all$diff,y=all$is_merged,method="spearman")$p.value
print(c(each_corr,each_p_value))

each_corr=cor.test(x=all$diff,y=all$time_close,method="spearman")$estimate
each_p_value=cor.test(x=all$diff,y=all$time_close,method="spearman")$p.value
print(c(each_corr,each_p_value))
